### ISSUE TITLE
snRNA-seq analyses

### ISSUE THREAD

**Issue by lmweber** [lmweber/locus-c#13]

**Comment by lmweber** [comment]
Experiments currently underway

Analyses:
- use to generate reference profiles of major cell types (NE neurons, other)
- use as input for spot-level deconvolution, e.g. using SPOTlight or other methods

**Comment by lmweber** [comment]
Generate count matrices with Cell Ranger v6 @mattntran

**Comment by lmweber** [comment]
QC @mattntran
- Emptydrops for nuclei calling
- mitochondrial QC / check distributions
- doublet score with computeDoubletDensity / check clusters downstream

**Comment by lmweber** [comment]
Feature selection @mattntran
- modelGeneVar / PCA
- try GLM-PCA / scry instead

**Comment by lmweber** [comment]
Batch integration
- fastMNN and/or Harmony
- to check for donor effect

**Comment by lmweber** [comment]
Clustering
- graph-based kNN
- how many clusters?
- pseudobulk hierarchical clustering if too many clusters? but may merge the wrong clusters

**Comment by lmweber** [comment]
Markers defining the generated clusters (depending on resolution)

**Comment by mattntran** [comment]
> Clustering
> 
> * graph-based kNN
> * how many clusters?
> * pseudobulk hierarchical clustering if too many clusters? but may merge the wrong clusters

Forgot to add in our discussion I like `getClusteredPCs()` for defining my working PC space (with whichever PCA method), which tests clustering behavior in d+1 (10, 11, 12, ... D) PCs.
