### ISSUE TITLE
Shiny app

### ISSUE THREAD

**Issue by lmweber** [lmweber/locus-c#18]
Set up a Shiny app for manually annotating regions:
- @lcolladotor to provide links to documentation
- use high-resolution image (2000 pixels)
- may need update to Shiny app to allow selecting high-resolution image

**Comment by lcolladotor** [comment]
# Documentation

* http://research.libd.org/spatialLIBD/articles/TenX_data_download.html: explains what parts you need to add to the `spe` to support the `shiny` web app in `spatialLIBD`.
* https://lmweber.org/OSTA-book/spatiallibd-workflow.html: revisits some of that information but also shows how to deploy the app.
* (new!): http://research.libd.org/spatialLIBD/articles/TenX_data_download.html#wrapper-functions: functions that read in the output from `SpaceRanger` and make it easy to then deploy a `spatialLIBD` app

# Code

* https://github.com/LieberInstitute/Visium_IF_AD/blob/master/code/04_build_spe/build_basic_spe.R: for using `spatialLIBD::read10xVisiumWrapper()`
* https://github.com/LieberInstitute/Visium_IF_AD/tree/master/code/05_deploy_app: code based on https://github.com/lmweber/OSTA-book/tree/main/spatialLIBD_demo

# Deployment settings

<img width="633" alt="Screen Shot 2021-11-11 at 12 16 31 AM" src="https://user-images.githubusercontent.com/2288213/141242299-7fc7d634-b6d8-4b87-8959-39d5dcc02258.png">

* Those were the settings from https://jhubiostatistics.shinyapps.io/spatialLIBD_mirror01/. Note that without more read time than the default and more memory than the default, the app might not even load.
* You'll likely have to check the logs on shinyapps.io to troubleshoot.

# Example apps

* https://libd.shinyapps.io/Visium_IF_AD_Kwon2021/ (working on it)
* https://libd.shinyapps.io/OSTA_spatialLIBD_demo/ (not updated)

# Issues

* As of today, shinyapps.io doesn't support R 4.1.2. So I had to install R 4.1.1 with Bioconductor 3.14 (and `BiocManager::install("LieberInstitute/spatialLIBD")`; note that you have to install from GitHub and not from a local git clone).
* It should work with R 4.1.1 and Bioconductor 3.15, but well, I wanted to avoid dealing with updates in `SpatialExperiment` for now.

**Comment by lcolladotor** [comment]
Here you can download R 4.1.1 for macOS if you need to https://cran.r-project.org/bin/macosx/base/

**Comment by lmweber** [comment]
Thanks @lcolladotor for these instructions!

Code for the Shiny app is now here: https://github.com/lmweber/locus-c/tree/main/code/analyses/5_shiny_app

**Comment by lmweber** [comment]
One strange error I am getting is that running the app gives the following error when using the latest version of `shiny` package 1.7.1. It works fine with the older version of `shiny` 1.6.0.

This error also occurs in the examples from `spatialLIBD` documentation with `shiny` 1.7.1. I found the suggestion to use `shiny` 1.6.0 somewhere on google, but I don't know why this fixes it.

![Screen Shot 2021-11-16 at 14 29 57](https://user-images.githubusercontent.com/8062417/142055067-3048aaec-6ba3-4344-bff3-87022ed39080.png)

**Comment by lcolladotor** [comment]
Related to R 4.1.2: it looks like they are working on adding support to R 4.1.2 https://community.rstudio.com/t/error-unhandled-exception-child-task-1049745496-failed-error-building-image-r-version-4-1-2-currently-unavailable/121461

https://community.rstudio.com/t/shinyapps-problem/120258/4 is from 8 days ago so maybe it'll be done soon.

**Comment by lmweber** [comment]
Ok seems to be working now! https://libd.shinyapps.io/Locus_coeruleus/

**Comment by lcolladotor** [comment]
FYI, Abby and I noticed this today:

<img width="805" alt="Screen Shot 2021-11-23 at 5 49 06 PM" src="https://user-images.githubusercontent.com/2288213/143141255-2425acf3-e8ee-4cd7-abdb-36049d8cb422.png">

**Comment by lmweber** [comment]
Oh cool thanks! Will upgrade back to R 4.1.2 in that case.

**Comment by lmweber** [comment]
Feedback from Kristen: to annotate spots accurately, we need to be able to show spots with the correct radius in the interactive / zoomable gene viewer.

This will require:
- storing the spot radius in the SpatialExperiment object (see issue https://github.com/drighelli/SpatialExperiment/issues/25)
- modifying the `spatialLIBD` app to allow displaying customized spot radius (see issue https://github.com/LieberInstitute/spatialLIBD/issues/28)

**Comment by lmweber** [comment]
Updated tasks for finalizing Shiny app:
- [ ] update `SpatialExperiment` object in latest `SpatialExperiment` format and re-deploy app
- [ ] update information pages
