### ISSUE TITLE
Figure 1 - schematic and experimental design

### ISSUE THREAD

**Issue by lmweber** [lmweber/locus-c#7]
Create a draft layout for Figure 1 on overall schematic and experimental design.

This may include:
- schematic on the overall workflow
- experimental design - e.g. number of donors, demographics, dissection strategy
- quality control (QC) with RNAscope
- details on Visium protocol
- images of LC tissue block, RNAscope, H&E sections
- schematic of how tissue was put on arrays

For some ideas we can also look at Figure 1 in our [previous DLPFC paper](https://www.nature.com/articles/s41593-020-00787-0).

For more details see also Keri's Slack message in LC channel on 2021/09/08.

**Comment by lmweber** [comment]
Assign to @heenadivecha

**Comment by lmweber** [comment]
Updating this issue with remaining tasks for this figure from our discussion this week:

Figure 1: experimental design and overview
- [ ] updates to figure panels and formatting
- [ ] update draft figure caption
- [ ] add draft text paragraphs
- [ ] add Supplementary Table 1: summary of experimental design and sample information, including donor information

**Comment by heenadivecha** [comment]
Fig.1 has been made and is shared with others using oneDrive.
